[package]
name = "mul_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = { version = "1.0", features = ["c++17"] }

[build-dependencies]
cxx-build = "1.0"

[lib]
crate-type=["staticlib"]
